services:
  web:
    build: .
    volumes:
      - ./app_data.db:/app/app_data.db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginx config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Static file
      - ./static:/app/static:ro
      # Cloudflare Origin Certificates folder
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
    restart: unless-stopped